"""One song job end to end: generation, mastering, mp3, Whisper sung-lyrics check.

**Music3 is never actually run here** -- it needs the GPU, and the GPU may be busy with something
else entirely (H3 and Music3 do not coexist, design spec, "Трек"). Every `run_song`/`_generate_wav`/
`_transcribe` test substitutes a fake `run` callable in place of `subprocess.run`, mirroring
`test_worker.py`'s `spawn` substitution for the same reason. The one exception is `master`/`to_mp3`
(the ffmpeg mastering chain): those *are* exercised against a real `ffmpeg`, fed a synthetic sine
wave generated by `ffmpeg -f lavfi` -- no GPU, no external model, just the mastering chain itself.

The Whisper fuzzy-matching tests (`check_lyrics_sung` and friends) are pure functions -- no
subprocess at all -- and are built directly from the 2026-08-18 "Колыбельная" run's real facts: a
268 s take against a 295 s cap that was *not* undersung (Music3 simply ran out of lyrics), a real
Whisper mishearing ("в висках" -> "песка"), and an undersung take that looks like a sung head and
an unsung tail, not a short recording.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

from h3_48gb import songrun as sr

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = Path(__file__).resolve().parent / "data"


# -- estimate_duration / count_sections ----------------------------------------------------------


def test_count_sections_counts_every_tag_occurrence_including_repeats():
    lyrics = "[intro]\nline one\n\n[chorus]\nline two\n\n[chorus]\nline three\n\n[outro]\nline four"
    assert sr.count_sections(lyrics) == 4


def test_count_sections_on_the_real_kolybelnaya_lyrics_is_eleven():
    # intro, verse, verse, pre-chorus, chorus, verse, pre-chorus, chorus, bridge, verse, chorus,
    # outro -- but written out as the real file has it (verse/pre-chorus/chorus each split into
    # two stanzas under one tag counts as one section, matching the real lyric's own tagging).
    lyrics = """
[intro]
Спи, мой маленький, мой ясный,
Свет мой, тихий лепесток.

[verse]
Слышишь - старый верный Альдред
Тихо ходит у дверей.

За восточною стеною,
Где течёт ночной поток.

[pre-chorus]
Не пугайся, мой родимый,
Тих и тёпел этот час.

[chorus]
Спи, мой князь, мой белый сокол,
Спи, моё родное сердце.

[verse]
Слышишь - там, внизу, у двери
Ходит ветер тяжело.

[pre-chorus]
Я тебе под ушко тихо
Положу свой перстень-знак.

[chorus]
Спи, мой князь, мой белый сокол,
Спи, моё родное сердце.

[bridge]
Альдред здесь. Иди, мой милый,
Поцелуй меня в чело.

[verse]
А теперь - закрою двери,
А теперь - возьму клинок.

[chorus]
Спи, мой князь, мой белый сокол,
Ты вернёшься через век.

[outro]
Спи, мой светлый.
Спи, мой князь.
"""
    assert sr.count_sections(lyrics) == 11


def test_estimate_duration_is_28s_per_section_plus_15s_pad():
    lyrics = "[intro]\na\n\n[chorus]\nb\n\n[outro]\nc"
    assert sr.estimate_duration(lyrics) == pytest.approx(28.0 * 3 + 15.0)


def test_estimate_duration_of_untagged_lyrics_is_one_implicit_section():
    lyrics = "just some words\nwith no tags at all"
    assert sr.count_sections(lyrics) == 1
    assert sr.estimate_duration(lyrics) == pytest.approx(28.0 + 15.0)


def test_estimate_duration_of_empty_lyrics_is_just_the_pad():
    assert sr.estimate_duration("") == pytest.approx(15.0)


# -- check_lyrics_sung: fuzzy line/segment matching ----------------------------------------------


def _seg(start, end, text):
    return {"start": start, "end": end, "text": text}


def test_a_fully_sung_short_song_is_not_undersung_and_every_section_gets_a_start():
    lyrics = "[intro]\nСпи мой маленький\n\n[chorus]\nСпи мой князь мой белый сокол"
    segments = [
        _seg(0.0, 3.0, "Спи мой маленький"),
        _seg(3.0, 7.0, "Спи мой князь мой белый сокол"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=7.0)
    assert undersung is False
    assert sections == [
        {"name": "intro", "start": 0.0, "end": 3.0},
        {"name": "chorus", "start": 3.0, "end": 7.0},
    ]


def test_whisper_mishearing_v_viskah_to_peska_still_matches_at_50_percent_overlap():
    """The real 2026-08-18 example: Whisper heard "Имя древнее песка" for the sung line "Имя
    древнее в висках". 2 of the line's 4 words survive -- exactly the 50% floor
    `LINE_MATCH_THRESHOLD` is pinned to. This must match, or a correctly-sung chorus line would be
    wrongly counted against the undersung gate.
    """
    line_words = sr._word_set("Имя древнее в висках")
    heard_words = sr._word_set("Имя древнее песка")
    assert sr._overlap(line_words, heard_words) == pytest.approx(0.5)
    assert sr._overlap(line_words, heard_words) >= sr.LINE_MATCH_THRESHOLD


# -- I5: an absolute word-count floor alongside the 50% fraction --------------------------------


def test_i5_word_floor_rejects_a_short_line_at_50_percent_with_only_one_shared_word():
    """`LINE_MATCH_THRESHOLD`'s *fraction* alone is not enough for a short line -- a 2-word line
    clears 50% with just one shared word. `MIN_SHARED_WORDS` (2026-08-18 review, I5) adds an
    absolute floor of 2 shared words on top of the fraction, so a short line's thin, coincidental
    overlap with an unrelated segment (the real report: the outro's short "Спи, мой князь." class
    of line, built from words -- "спи", "мой" -- that recur all over the song) can no longer clear
    the bar alone.
    """
    line_words = sr._word_set("Спи, мой.")
    foreign_words = sr._word_set("мой дорогой друг")
    assert sr._overlap(line_words, foreign_words) == pytest.approx(0.5)
    assert not sr._line_matches_segment(line_words, foreign_words)


def test_i5_word_floor_does_not_reject_the_real_mishearing_regression():
    """The floor must not raise the *effective* bar above 50% for a normal-length line -- the real
    "в висках" -> "песка" mishearing shares exactly 2 words and must still pass both the fraction
    and the floor (this is `MIN_SHARED_WORDS`'s own value, not a coincidence).
    """
    line_words = sr._word_set("Имя древнее в висках")
    heard_words = sr._word_set("Имя древнее песка")
    assert sr._line_matches_segment(line_words, heard_words)


def test_check_lyrics_sung_matches_the_mishearing_end_to_end():
    lyrics = "[chorus]\nИмя древнее в висках"
    segments = [_seg(10.0, 13.0, "Имя древнее песка")]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=13.0)
    assert sections == [{"name": "chorus", "start": 10.0, "end": 13.0}]
    assert undersung is False


def test_268_of_295_seconds_with_a_fully_sung_tail_is_not_undersung():
    """Music3 stopping early once the lyrics run out (268s audio, 295s cap) is not undersung by
    itself -- what matters is whether the *lyrics'* tail was sung, which this fixture makes true.
    """
    lyrics = "\n".join([
        "[verse]",
        "line one",
        "line two",
        "line three",
        "[outro]",
        "line four",
        "line five",
        "line six",
    ])
    segments = [
        _seg(0.0, 10.0, "line one"),
        _seg(10.0, 20.0, "line two"),
        _seg(20.0, 30.0, "line three"),
        _seg(30.0, 40.0, "line four"),
        _seg(40.0, 50.0, "line five"),
        _seg(50.0, 60.0, "line six"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=268.0)
    assert undersung is False
    assert sections[-1]["end"] == 268.0


def test_undersung_take_has_a_sung_head_and_an_unsung_tail():
    """Shape lifted from the real "Колыбельная" undersung diagnosis: the bridge sings fine, then
    the final chorus/outro go completely unmatched while the audio (per the design spec) keeps
    playing as instrumental. Every line uses its own distinct vocabulary -- no shared filler word
    across lines -- so a line cannot spuriously clear the 50% overlap floor against an unrelated
    already-matched segment merely by sharing one common word with it.
    """
    lyrics = "\n".join([
        "[bridge]", "альдред здесь иди милый", "поцелуй меня чело",
        "[verse]", "закрою двери клинок", "король оставил веру",
        "[chorus]", "спи мой белый сокол", "имя древнее столетья",
        "[outro]", "спи мой светлый князь", "мать твоя стража",
    ])
    segments = [
        _seg(0.0, 5.0, "альдред здесь иди милый"),
        _seg(5.0, 10.0, "поцелуй меня чело"),
        _seg(10.0, 15.0, "закрою двери клинок"),
        _seg(15.0, 20.0, "король оставил веру"),
        # final chorus and outro: not sung -- only a trailing hallucinated segment with no
        # relation to the lyrics at all (e.g. a fade-out caption-credit artifact).
        _seg(20.0, 24.0, "субтитры делал дима торжок"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=24.0)
    assert undersung is True
    by_name = {s["name"]: s for s in sections}
    assert by_name["bridge"]["start"] == 0.0
    assert by_name["verse"]["start"] == 10.0
    assert by_name["chorus"]["start"] is None
    assert by_name["outro"]["start"] is None


def test_a_hallucinated_tail_segment_with_no_match_is_simply_ignored():
    lyrics = "[outro]\nSpi moy svetlyy"
    segments = [
        _seg(0.0, 2.0, "Spi moy svetlyy"),
        _seg(2.0, 6.0, "субтитры делал дима торжок"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=6.0)
    assert undersung is False
    assert sections == [{"name": "outro", "start": 0.0, "end": 6.0}]


def test_a_repeated_section_name_gets_two_separate_entries_matched_in_order():
    lyrics = "\n".join([
        "[chorus]", "spi moy knyaz",
        "[verse]", "middle line",
        "[chorus]", "spi moy knyaz",
    ])
    segments = [
        _seg(0.0, 3.0, "spi moy knyaz"),
        _seg(3.0, 6.0, "middle line"),
        _seg(6.0, 9.0, "spi moy knyaz"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=9.0)
    assert len(sections) == 3
    assert [s["name"] for s in sections] == ["chorus", "verse", "chorus"]
    assert sections[0]["start"] == 0.0
    assert sections[2]["start"] == 6.0, "second chorus must not match the first chorus's segment"


# -- C1 regression: a repeated section must not steal an earlier occurrence's segment -----------


def test_c1_minimal_repro_second_identical_section_does_not_steal_the_first_ones_segment():
    """Minimal synthetic repro (2026-08-18 review, C1). Four short lines, packed two-per-segment
    into two Whisper segments -- realistic packing granularity (a segment spanning 2 short lyric
    lines is normal; the whole 4-line section landing in one giant segment is not, and is not what
    this reproduces) -- followed by an identical repeat of all four lines with no segments of its
    own at all (the second occurrence was never actually re-recorded).

    With the old `pointer = found` (never advancing past a claimed segment), the repeat's lines
    could walk straight back into the first occurrence's own last-claimed segment purely because
    the text was identical -- stealing its timestamp for the (unsung) second occurrence and, via
    `_section_ends`, truncating the first occurrence's own `end` to that same stolen value.
    """
    lyrics = "\n".join([
        "[chorus]", "hello world", "foo bar", "baz qux", "quux corge",
        "[chorus]", "hello world", "foo bar", "baz qux", "quux corge",
    ])
    segments = [
        _seg(10.0, 15.0, "hello world foo bar"),
        _seg(15.0, 20.0, "baz qux quux corge"),
    ]

    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=30.0)
    assert sections[0] == {"name": "chorus", "start": 10.0, "end": 30.0}, (
        "the first (really sung) chorus's end must reach the track duration, not get truncated "
        "by the unsung repeat")
    assert sections[1] == {"name": "chorus", "start": None, "end": None}, (
        "the second, unsung chorus must not steal the first chorus's segments just because the "
        "lyric text is identical")
    assert undersung is True


def test_c1_fixture_repro_real_kolybelnaya_chorus_repeated_second_occurrence_unsung():
    """Real-data regression (2026-08-18 review, C1) built from the actual "Колыбельная" fixture
    (`tests/data/kolybelnaya-lyrics.txt`/`kolybelnaya-whisper.txt`) -- this is the real bug the
    reviewer reproduced: a repeated `[chorus]` (the real lyric's own chorus text, which really does
    recur verbatim) where the second occurrence was not actually sung got assigned a start *inside*
    the first occurrence's own span, and the first occurrence's `end` got truncated to that stolen
    value.

    The lyric lines and the Whisper wording (including the real mishearing "в висках" ->
    "песка") are copied verbatim from the fixture files; only the segment timestamps are synthetic
    (the fixture's `whisper.txt` is flat text with no timestamps at all) and only the "two
    occurrences back to back, second one unsung" arrangement is this test's own construction --
    picked to isolate the exact pointer bug from the rest of the song. Segments are packed 2 real
    lines each, matching Whisper's real few-seconds-per-segment granularity, not one giant blob for
    the whole chorus.
    """
    lyrics_text = (DATA_DIR / "kolybelnaya-lyrics.txt").read_text(encoding="utf-8")
    whisper_text = (DATA_DIR / "kolybelnaya-whisper.txt").read_text(encoding="utf-8")
    assert "песка" in whisper_text, "fixture must contain the real в висках -> песка mishearing"

    section_names, lines = sr.parse_lyrics(lyrics_text)
    chorus_lines = [text for idx, text in lines if section_names[idx] == "chorus"][:8]
    assert len(chorus_lines) == 8
    lyrics = "[chorus]\n" + "\n".join(chorus_lines) + "\n[chorus]\n" + "\n".join(chorus_lines)

    # The real Whisper transcript's own wording for these 8 lines (kolybelnaya-whisper.txt),
    # mishearings and all -- "в висках" -> "песка", "лишь тьма" -> "лилишь тьма".
    heard = [
        "Спи, мой князь, мой белый сокол", "Спи, мое родное сердце",
        "Имя древнее песка", "Пронеси сквозь все столетия",
        "Спи, мой светлый, не услышишь", "Как над башней лилишь тьма",
        "Только знай, над низкой крышей", "Ждет восток и в нем заря",
    ]
    segments = []
    t = 80.0
    for i in range(0, 8, 2):
        segments.append(_seg(t, t + 3.5, heard[i] + " " + heard[i + 1]))
        t += 3.5

    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=95.0)
    assert sections[0]["start"] == 80.0
    assert sections[0]["end"] == 95.0, "first chorus's end must not be truncated by the repeat"
    assert sections[1] == {"name": "chorus", "start": None, "end": None}, (
        "the unsung second chorus must not steal a timestamp from inside the first chorus")
    assert undersung is True


def test_undersung_threshold_is_exactly_60_percent_of_the_last_third():
    # 9 lines (2 words each -- MIN_SHARED_WORDS's floor needs >= 2 shared words to match at all)
    # -> last third is lines[6:], 3 lines. 2/3 matched = 66.7% -> not undersung.
    lyrics = "\n".join(f"line{i} word{i}" for i in range(9))
    segments = [_seg(float(i), float(i) + 1, f"line{i} word{i}") for i in range(9) if i not in (7,)]
    _, undersung = sr.check_lyrics_sung(lyrics, segments)
    assert undersung is False

    # Drop one more of the last three matches (now 1/3 = 33%) -> undersung.
    segments_worse = [_seg(float(i), float(i) + 1, f"line{i} word{i}")
                       for i in range(9) if i not in (7, 8)]
    _, undersung_worse = sr.check_lyrics_sung(lyrics, segments_worse)
    assert undersung_worse is True


def test_undersung_threshold_boundary_is_exactly_60_percent_not_a_hair_below():
    """The minor from the 2026-08-18 review: an exact-60% case, not just "somewhere above/below
    60%" -- 5 lines in the tail, exactly 3 matched = 0.6 = `UNDERSUNG_LINE_THRESHOLD` itself, and
    `undersung` is defined as strictly *below* the threshold, so exactly-60% must NOT be undersung.
    """
    # 15 lines -> last third is lines[10:], 5 lines. 2-word lines to clear MIN_SHARED_WORDS.
    lyrics = "\n".join(f"line{i} word{i}" for i in range(15))
    # Match all of the first two-thirds (10 lines) plus exactly 3 of the last 5 (indices 10-12).
    matched = list(range(10)) + [10, 11, 12]
    segments = [_seg(float(i), float(i) + 1, f"line{i} word{i}") for i in matched]
    _, undersung = sr.check_lyrics_sung(lyrics, segments)
    assert undersung is False, "exactly 60% of the tail matched must not count as undersung"


def test_i1_section_ends_gives_none_end_to_a_section_with_no_start():
    """I1 (2026-08-18 review): a section whose own `start` is `None` (nothing in it matched) must
    always get `end=None` too -- there is no timestamp to anchor either boundary to. Before the
    fix, `_section_ends` computed `end[i]` from "the next known start after i" regardless of
    whether `starts[i]` itself was `None`, so an unsung section in the *middle* of the list could
    still inherit a real `end` value that belonged to a section after it.
    """
    starts = [0.0, None, 5.0]
    ends = sr._section_ends(starts, duration=20.0)
    assert ends == [5.0, None, 20.0]


def test_i1_section_ends_trailing_none_start_also_gets_none_end():
    starts = [0.0, 5.0, None]
    ends = sr._section_ends(starts, duration=20.0)
    assert ends == [5.0, 20.0, None]


def test_check_lyrics_sung_on_empty_lyrics_is_not_undersung():
    sections, undersung = sr.check_lyrics_sung("", [])
    assert sections == []
    assert undersung is False


# -- C2: MASTER_FILTER's exact EQ chain, confirmed by the chain's owner -------------------------


def test_c2_master_filter_is_the_full_seven_entry_eq_chain():
    """C2 (2026-08-18 review): the plan-brief's EQ chain was a five-entry transcription shortcut,
    not the actual proven chain -- the owner confirmed the full seven-entry `firequalizer` curve.
    Pinned as an exact-string regression so this cannot silently drift back to a shortened version.
    """
    assert sr.MASTER_FILTER == (
        "highpass=f=38,"
        "firequalizer=gain_entry='entry(60,-2.5);entry(120,-1.5);entry(3000,1.5);entry(5000,2);"
        "entry(8000,3.5);entry(12000,4);entry(16000,3)',"
        "loudnorm=I=-13.6:TP=-1:LRA=11"
    )


# -- master / to_mp3: the one real-ffmpeg test -----------------------------------------------


def _make_sine_wav(path: Path, duration: float = 2.0) -> None:
    cmd = ["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi",
           "-i", f"sine=frequency=440:duration={duration}", str(path)]
    subprocess.run(cmd, check=True, capture_output=True)


def _ffprobe_duration(path: Path) -> float:
    cmd = ["ffprobe", "-v", "error", "-show_entries", "format=duration",
           "-of", "default=noprint_wrappers=1:nokey=1", str(path)]
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return float(result.stdout.strip())


def test_master_and_to_mp3_run_a_real_ffmpeg_on_a_synthetic_sine(tmp_path):
    wav = tmp_path / "sine.wav"
    _make_sine_wav(wav, duration=2.0)

    mastered = sr.master(wav, tmp_path / "sine.mastered.wav")
    assert mastered == tmp_path / "sine.mastered.wav"
    assert mastered.is_file()
    assert mastered.stat().st_size > 0
    assert _ffprobe_duration(mastered) == pytest.approx(2.0, abs=0.2)

    mp3 = sr.to_mp3(wav, tmp_path / "sine.mp3")
    mastered_mp3 = sr.to_mp3(mastered, tmp_path / "sine.mastered.mp3")
    for out in (mp3, mastered_mp3):
        assert out.is_file()
        assert out.stat().st_size > 0
        assert _ffprobe_duration(out) == pytest.approx(2.0, abs=0.3)


def test_master_raises_song_run_error_on_a_missing_input_file(tmp_path):
    with pytest.raises(sr.SongRunError):
        sr.master(tmp_path / "does-not-exist.wav", tmp_path / "out.wav")


# -- I6: _run wraps a bare OSError/FileNotFoundError, never lets one escape ----------------------


def test_i6_run_wraps_oserror_as_song_run_error():
    """I6 (2026-08-18 review): if `run` itself raises (e.g. the resolved binary does not exist --
    `_mlx_whisper_binary`'s own docstring flags this as a real, unguarded risk), `_run` must not
    let a bare `OSError`/`FileNotFoundError` escape -- the caller (task 3's worker glue) catches
    exactly one exception type for "this song job failed", the same discipline `_run` already
    applies to a nonzero exit code.
    """
    def broken_run(cmd, **kwargs):
        raise FileNotFoundError("no such file: fake-binary")

    with pytest.raises(sr.SongRunError, match="fake-binary"):
        sr._run(["fake-binary"], broken_run, "fake step")


def test_i6_run_or_raise_wraps_oserror_as_song_run_error():
    def broken_run(cmd, **kwargs):
        raise OSError("permission denied")

    with pytest.raises(sr.SongRunError, match="permission denied"):
        sr._run_or_raise(["fake-binary"], broken_run, "fake step")


# -- _mlx_whisper_binary ---------------------------------------------------------------------


def test_mlx_whisper_binary_is_the_console_script_next_to_the_python_interpreter(tmp_path):
    venv_bin = tmp_path / "venv" / "bin"
    venv_bin.mkdir(parents=True)
    python = venv_bin / "python"
    python.touch()
    assert sr._mlx_whisper_binary(python) == venv_bin / "mlx_whisper"


def test_mlx_whisper_binary_does_not_follow_the_venv_python_symlink_out_of_the_venv(tmp_path):
    """P0 первого живого song-job'а (ворота 2026-08-19): `bin/python` в venv — симлинк-цепочка
    на базовый интерпретатор pyenv, и `.resolve()` уводил поиск console-script'а из venv в
    pyenv-`bin/`, где `mlx_whisper` не существует. Скрипт лежит рядом с симлинком, не рядом
    с его целью."""
    base_bin = tmp_path / "pyenv" / "bin"
    base_bin.mkdir(parents=True)
    real_python = base_bin / "python3"
    real_python.touch()
    venv_bin = tmp_path / "venv" / "bin"
    venv_bin.mkdir(parents=True)
    python = venv_bin / "python"
    python.symlink_to(real_python)
    (venv_bin / "mlx_whisper").touch()
    found = sr._mlx_whisper_binary(python)
    assert found == venv_bin / "mlx_whisper"
    assert found.exists()


# -- fake subprocess plumbing: _generate_wav / _transcribe / run_song -------------------------


class _FakeRun:
    """Stands in for `subprocess.run`: records every call and, per call, either runs a canned
    side effect (writing whatever file a real subprocess would have written) or just returns a
    canned `CompletedProcess`-shaped result. Matches by the second argv element (the script/binary
    name), the same way a human would recognize which of `run_song`'s four subprocess calls just
    ran.
    """

    def __init__(self):
        self.calls: list[list[str]] = []
        self.handlers = {}

    def add(self, matcher, handler):
        self.handlers[matcher] = handler

    def __call__(self, cmd, **kwargs):
        self.calls.append(cmd)
        for matcher, handler in self.handlers.items():
            if matcher(cmd):
                return handler(cmd)
        raise AssertionError(f"no fake handler matched {cmd}")


class _Result:
    def __init__(self, returncode=0, stdout="", stderr=""):
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr


def _is_generate_call(cmd):
    return cmd[1] == str(sr.MUSIC3_GENERATE_SCRIPT)


def _is_mlx_whisper_call(cmd):
    return Path(cmd[0]).name == "mlx_whisper"


def _is_ffmpeg_call(cmd):
    return cmd[0] == "ffmpeg"


def test_generate_wav_parses_the_actual_duration_from_stdout(tmp_path):
    fake = _FakeRun()

    def handle_generate(cmd):
        out_path = Path(cmd[cmd.index("--output") + 1])
        out_path.write_bytes(b"fake wav bytes")
        stdout = ("[timing] model load: 3.5 s\n"
                  "[audio] " + str(out_path) + "  shape=(100, 2)  sr=44100  dur=268.3s\n")
        return _Result(returncode=0, stdout=stdout)

    fake.add(_is_generate_call, handle_generate)

    wav_path, duration = sr._generate_wav(
        "python3", "modeldir", "caption text", "lyrics text", 295.0, 30, 7, tmp_path, run=fake)

    assert wav_path == tmp_path / "song.wav"
    assert wav_path.is_file()
    assert duration == pytest.approx(268.3)
    assert (tmp_path / "caption.txt").read_text(encoding="utf-8") == "caption text"
    assert (tmp_path / "lyrics.txt").read_text(encoding="utf-8") == "lyrics text"
    assert "dur=268.3s" in (tmp_path / "gen.log").read_text(encoding="utf-8")

    [cmd] = fake.calls
    assert cmd[0] == "python3"
    assert "--duration" in cmd and cmd[cmd.index("--duration") + 1] == "295.0"
    assert "--seed" in cmd and cmd[cmd.index("--seed") + 1] == "7"


def test_generate_wav_raises_on_nonzero_exit(tmp_path):
    fake = _FakeRun()
    fake.add(_is_generate_call, lambda cmd: _Result(returncode=1, stderr="boom"))
    with pytest.raises(sr.SongRunError, match="boom"):
        sr._generate_wav("python3", "modeldir", "c", "l", 90.0, 30, 7, tmp_path, run=fake)


def test_generate_wav_raises_when_stdout_has_no_dur_line(tmp_path):
    fake = _FakeRun()
    fake.add(_is_generate_call, lambda cmd: _Result(returncode=0, stdout="no useful line here"))
    with pytest.raises(sr.SongRunError, match="dur="):
        sr._generate_wav("python3", "modeldir", "c", "l", 90.0, 30, 7, tmp_path, run=fake)


def test_i3_generate_wav_writes_gen_log_before_raising_on_a_nonzero_exit(tmp_path):
    """I3 (2026-08-18 review): `gen.log` must land on disk *before* `_generate_wav` raises on a
    nonzero exit code -- Music3's own stdout (the `[timing]`/peak-memory lines) is the only
    diagnostic this module has for a failed generation, and it must survive the failure.
    """
    fake = _FakeRun()
    fake.add(_is_generate_call, lambda cmd: _Result(
        returncode=1, stdout="[timing] model load: 3.5 s\n[mem] peak=41.2 GB\n", stderr="cuda OOM"))

    with pytest.raises(sr.SongRunError, match="cuda OOM"):
        sr._generate_wav("python3", "modeldir", "c", "l", 90.0, 30, 7, tmp_path, run=fake)

    log = (tmp_path / "gen.log").read_text(encoding="utf-8")
    assert "model load" in log
    assert "peak=41.2 GB" in log
    assert "cuda OOM" in log


def test_transcribe_reads_back_the_json_the_cli_would_have_written(tmp_path):
    fake = _FakeRun()

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        payload = {"text": "hello", "segments": [{"start": 0.0, "end": 1.0, "text": "hello"}]}
        (out_dir / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
        return _Result(returncode=0)

    fake.add(_is_mlx_whisper_call, handle_whisper)

    data = sr._transcribe(tmp_path / "python", tmp_path / "audio.wav", tmp_path, run=fake)
    assert data["text"] == "hello"
    assert data["segments"][0]["text"] == "hello"

    [cmd] = fake.calls
    assert Path(cmd[0]).name == "mlx_whisper"
    assert "--language" in cmd and cmd[cmd.index("--language") + 1] == "ru"
    assert "--model" in cmd and cmd[cmd.index("--model") + 1] == sr.WHISPER_MODEL


def test_transcribe_raises_if_the_json_file_never_appears(tmp_path):
    fake = _FakeRun()
    fake.add(_is_mlx_whisper_call, lambda cmd: _Result(returncode=0))  # writes nothing
    with pytest.raises(sr.SongRunError):
        sr._transcribe(tmp_path / "python", tmp_path / "audio.wav", tmp_path, run=fake)


def test_transcribe_raises_on_nonzero_exit(tmp_path):
    fake = _FakeRun()
    fake.add(_is_mlx_whisper_call, lambda cmd: _Result(returncode=1, stderr="no weights"))
    with pytest.raises(sr.SongRunError, match="no weights"):
        sr._transcribe(tmp_path / "python", tmp_path / "audio.wav", tmp_path, run=fake)


# -- run_song: full orchestration with every subprocess faked ---------------------------------


def _wire_full_fake_pipeline(track_dir: Path, *, whisper_segments, whisper_text="",
                              audio_dur="90.0"):
    fake = _FakeRun()

    def handle_generate(cmd):
        out_path = Path(cmd[cmd.index("--output") + 1])
        out_path.write_bytes(b"fake raw wav")
        return _Result(stdout=f"[audio] {out_path}  shape=(1,2)  sr=44100  dur={audio_dur}s\n")

    def handle_ffmpeg(cmd):
        # the output path is always the last argv element for both master() and to_mp3()
        Path(cmd[-1]).write_bytes(b"fake ffmpeg output")
        return _Result()

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        payload = {"text": whisper_text, "segments": whisper_segments}
        (out_dir / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
        return _Result()

    fake.add(_is_generate_call, handle_generate)
    fake.add(_is_ffmpeg_call, handle_ffmpeg)
    fake.add(_is_mlx_whisper_call, handle_whisper)
    return fake


def test_run_song_wires_all_four_steps_into_a_song_result(tmp_path):
    track_dir = tmp_path / "track"
    segments = [{"start": 0.0, "end": 3.0, "text": "spi moy malenkiy"}]
    fake = _wire_full_fake_pipeline(track_dir, whisper_segments=segments,
                                     whisper_text="spi moy malenkiy", audio_dur="87.5")

    result = sr.run_song(
        track_dir, lyrics="[intro]\nspi moy malenkiy", caption="a lullaby", duration=90.0,
        seed=7, music3_python="fake-python3", model_dir="fake-model-dir", run=fake)

    assert isinstance(result, sr.SongResult)
    assert result.wav == track_dir / "song.wav"
    assert result.mastered_wav == track_dir / "song.mastered.wav"
    assert result.mp3 == track_dir / "song.mp3"
    assert result.mastered_mp3 == track_dir / "song.mastered.mp3"
    for path in (result.wav, result.mastered_wav, result.mp3, result.mastered_mp3):
        assert path.is_file()
    assert result.duration == pytest.approx(87.5)
    assert result.transcript == "spi moy malenkiy"
    assert result.sections == [{"name": "intro", "start": 0.0, "end": 87.5}]
    assert result.undersung is False

    # Whisper transcribed the *mastered* wav, not the raw take.
    whisper_call = next(c for c in fake.calls if Path(c[0]).name == "mlx_whisper")
    assert whisper_call[-1] == str(track_dir / "song.mastered.wav")


def test_run_song_result_fields_match_update_track_field_names():
    """`SongResult`'s field names line up 1:1 with `project.Project.update_track`'s accepted
    keywords for the fields this module actually produces -- task 3 hands the result straight
    through as `project.update_track(**{f: getattr(result, f) for f in (...)})`-shaped calls.

    Checked over the *entire* set of fields the two have in common (minor, 2026-08-18 review), not
    just a hand-picked subset -- a hard-coded `{"mp3", "mastered_mp3", "sections"}` subset (the
    original version of this test) would silently miss a future rename dropping e.g. `wav` from
    that overlap, since the subset check would keep passing either way.

    `undersung` joined this set in task 3: `_TRACK_FIELDS` grew an `undersung` field specifically so
    the worker's song-job dispatch (`h3_48gb.worker._run_song_job`) could pass
    `SongResult.undersung` straight through to `update_track(undersung=...)` the same way it already
    does for `wav`/`mp3`/`mastered_mp3`/`sections` -- see the task 3 report.

    `duration` joined this set in fix round 1 (I4, 2026-08-18 review): `_TRACK_FIELDS` grew a
    `duration` field so the same dispatch could pass `SongResult.duration` through too -- the
    track's actual length, from `run_song`'s own generated-audio measurement or `align_track`'s
    `ffprobe` read, not the `estimate_duration` guess `track.status` moved past long before either
    of those ever ran.
    """
    from h3_48gb import project as p
    result_fields = set(sr.SongResult.__dataclass_fields__)
    track_fields = set(p._TRACK_FIELDS)
    assert result_fields & track_fields == {
        "wav", "mp3", "mastered_mp3", "sections", "undersung", "duration", "raw_segments"}


def test_run_song_propagates_a_generation_failure_as_song_run_error(tmp_path):
    fake = _FakeRun()
    fake.add(_is_generate_call, lambda cmd: _Result(returncode=1, stderr="gpu busy"))
    with pytest.raises(sr.SongRunError, match="gpu busy"):
        sr.run_song(tmp_path / "track", lyrics="[intro]\nx", caption="c", duration=30.0, seed=1,
                    music3_python="p", model_dir="m", run=fake)


def test_run_song_flags_an_undersung_take(tmp_path):
    track_dir = tmp_path / "track"
    lyrics = "\n".join([
        "[verse]", "тихо ходит альдред", "унесет тебя сквозь сон", "восточная стена",
        "[outro]", "спи мой светлый князь", "мать твоя стража", "первый страж навек",
    ])
    # only the verse sung; the outro goes to a hallucinated tail segment -- no shared filler
    # words between lines, so a later line cannot spuriously overlap an earlier match.
    segments = [
        {"start": 0.0, "end": 2.0, "text": "тихо ходит альдред"},
        {"start": 2.0, "end": 4.0, "text": "унесет тебя сквозь сон"},
        {"start": 4.0, "end": 6.0, "text": "восточная стена"},
        {"start": 6.0, "end": 10.0, "text": "субтитры делал дима торжок"},
    ]
    fake = _wire_full_fake_pipeline(track_dir, whisper_segments=segments, audio_dur="10.0")
    result = sr.run_song(track_dir, lyrics=lyrics, caption="c", duration=90.0, seed=1,
                          music3_python="p", model_dir="m", run=fake)
    assert result.undersung is True


# -- I4: a retry starts clean, and a failed run never leaves a fake-finished mp3 behind ----------


def test_i4_run_song_removes_stale_song_and_whisper_files_before_generating(tmp_path):
    """I4 (2026-08-18 review): `run_song` deletes any `song.*`/`whisper.json` already in
    `track_dir` before doing anything else -- a half-finished take from an earlier failed attempt
    (task 3 retries with the *same* `track_dir`) must not be left sitting there looking like a
    complete, playable track once this run has actually finished.
    """
    track_dir = tmp_path / "track"
    track_dir.mkdir()
    (track_dir / "song.wav").write_bytes(b"stale half-finished take from a crashed retry")
    (track_dir / "song.mastered.mp3").write_bytes(b"stale mastered mp3 from a crashed retry")
    (track_dir / "whisper.json").write_text('{"stale": true}', encoding="utf-8")

    segments = [{"start": 0.0, "end": 3.0, "text": "spi moy malenkiy"}]
    fake = _wire_full_fake_pipeline(track_dir, whisper_segments=segments, audio_dur="10.0")
    result = sr.run_song(track_dir, lyrics="[intro]\nspi moy malenkiy", caption="c", duration=10.0,
                          seed=1, music3_python="p", model_dir="m", run=fake)

    assert result.wav.read_bytes() == b"fake raw wav"
    assert result.mastered_mp3.read_bytes() != b"stale mastered mp3 from a crashed retry"


def test_i4_run_song_propagates_a_mastering_failure_and_leaves_no_mastered_mp3(tmp_path):
    track_dir = tmp_path / "track"
    fake = _FakeRun()

    def handle_generate(cmd):
        out_path = Path(cmd[cmd.index("--output") + 1])
        out_path.write_bytes(b"fake raw wav")
        return _Result(stdout=f"[audio] {out_path}  shape=(1,2)  sr=44100  dur=10.0s\n")

    def handle_ffmpeg(cmd):
        return _Result(returncode=1, stderr="ffmpeg mastering exploded")

    fake.add(_is_generate_call, handle_generate)
    fake.add(_is_ffmpeg_call, handle_ffmpeg)

    with pytest.raises(sr.SongRunError, match="mastering exploded"):
        sr.run_song(track_dir, lyrics="[intro]\nx", caption="c", duration=10.0, seed=1,
                    music3_python="p", model_dir="m", run=fake)
    assert not (track_dir / "song.mastered.mp3").exists()


def test_i4_run_song_propagates_a_whisper_failure_and_leaves_no_mastered_mp3(tmp_path):
    track_dir = tmp_path / "track"
    fake = _FakeRun()

    def handle_generate(cmd):
        out_path = Path(cmd[cmd.index("--output") + 1])
        out_path.write_bytes(b"fake raw wav")
        return _Result(stdout=f"[audio] {out_path}  shape=(1,2)  sr=44100  dur=10.0s\n")

    def handle_ffmpeg(cmd):
        Path(cmd[-1]).write_bytes(b"fake ffmpeg output")
        return _Result()

    def handle_whisper(cmd):
        return _Result(returncode=1, stderr="mlx_whisper crashed: no such weights")

    fake.add(_is_generate_call, handle_generate)
    fake.add(_is_ffmpeg_call, handle_ffmpeg)
    fake.add(_is_mlx_whisper_call, handle_whisper)

    with pytest.raises(sr.SongRunError, match="mlx_whisper crashed"):
        sr.run_song(track_dir, lyrics="[intro]\nx", caption="c", duration=10.0, seed=1,
                    music3_python="p", model_dir="m", run=fake)
    assert not (track_dir / "song.mastered.mp3").exists()


# -- align_track: the import-only path ------------------------------------------------------------


def _is_ffprobe_call(cmd):
    return cmd[0] == "ffprobe"


def test_align_track_transcribes_the_mp3_as_given_and_uses_ffprobe_for_duration(tmp_path):
    """Fix round 1, I4 (2026-08-18 review): `duration` must come from `ffprobe`'s own read of the
    file's container-level length, not from the last Whisper segment's own end timestamp -- pinned
    here with an `ffprobe` duration that deliberately disagrees with (is longer than) the last
    segment's `end`, the exact shape a real imported mp3 with an unrecognized instrumental tail
    would have. The old, wrong implementation would have returned 3.0 (the last segment's `end`)
    here instead of 9.4.
    """
    track_dir = tmp_path / "track"
    mp3_path = tmp_path / "uploaded" / "suno-song.mp3"
    mp3_path.parent.mkdir(parents=True)
    mp3_path.write_bytes(b"fake mp3 bytes")

    fake = _FakeRun()
    segments = [{"start": 0.0, "end": 3.0, "text": "spi moy malenkiy"}]

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        payload = {"text": "spi moy malenkiy", "segments": segments}
        (out_dir / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
        return _Result()

    def handle_ffprobe(cmd):
        assert cmd[-1] == str(mp3_path)
        return _Result(stdout="9.4\n")

    fake.add(_is_mlx_whisper_call, handle_whisper)
    fake.add(_is_ffprobe_call, handle_ffprobe)

    result = sr.align_track(track_dir, mp3_path, "[intro]\nspi moy malenkiy",
                            music3_python="fake-python3", run=fake)

    assert isinstance(result, sr.SongResult)
    assert result.duration == pytest.approx(9.4), (
        "duration must come from ffprobe, not the last Whisper segment's own end")
    assert result.wav == mp3_path
    assert result.mastered_wav == mp3_path
    assert result.mp3 == mp3_path
    assert result.mastered_mp3 == mp3_path
    assert result.transcript == "spi moy malenkiy"
    assert result.sections == [{"name": "intro", "start": 0.0, "end": 9.4}]

    ffprobe_call = next(c for c in fake.calls if c[0] == "ffprobe")
    assert ffprobe_call == [*sr._FFPROBE_DURATION_CMD, str(mp3_path)]


def test_align_track_raises_song_run_error_if_ffprobe_fails(tmp_path):
    track_dir = tmp_path / "track"
    mp3_path = tmp_path / "song.mp3"
    mp3_path.write_bytes(b"fake mp3 bytes")

    fake = _FakeRun()

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        (out_dir / f"{name}.json").write_text(
            json.dumps({"text": "", "segments": []}), encoding="utf-8")
        return _Result()

    fake.add(_is_mlx_whisper_call, handle_whisper)
    fake.add(_is_ffprobe_call, lambda cmd: _Result(returncode=1, stderr="no such file"))

    with pytest.raises(sr.SongRunError, match="no such file"):
        sr.align_track(track_dir, mp3_path, "[intro]\nx", music3_python="p", run=fake)


def test_align_track_raises_song_run_error_on_unparseable_ffprobe_output(tmp_path):
    track_dir = tmp_path / "track"
    mp3_path = tmp_path / "song.mp3"
    mp3_path.write_bytes(b"fake mp3 bytes")

    fake = _FakeRun()

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        (out_dir / f"{name}.json").write_text(
            json.dumps({"text": "", "segments": []}), encoding="utf-8")
        return _Result()

    fake.add(_is_mlx_whisper_call, handle_whisper)
    fake.add(_is_ffprobe_call, lambda cmd: _Result(stdout="not-a-number\n"))

    with pytest.raises(sr.SongRunError, match="unparseable"):
        sr.align_track(track_dir, mp3_path, "[intro]\nx", music3_python="p", run=fake)


# -- align_track(lyrics=None): auto-lyrics (Task 1, "Сюжет клипа" wave) --------------------------


def test_align_track_with_no_reference_lyrics_returns_raw_segments_and_no_sections(tmp_path):
    """Design spec, "авто-лирика": a clip project may import an mp3 with no reference lyrics at
    all. `lyrics=None` must still run Whisper (the same transcription every other `align_track`
    call does) but skip the fuzzy-match against a reference that does not exist: `sections` comes
    back empty, `undersung` is always `False` (nothing to judge as unsung), and `raw_segments`
    carries Whisper's own segments -- trimmed to just `start`/`end`/`text`, not the full
    `mlx_whisper` segment dict.
    """
    track_dir = tmp_path / "track"
    mp3_path = tmp_path / "uploaded" / "no-lyrics-song.mp3"
    mp3_path.parent.mkdir(parents=True)
    mp3_path.write_bytes(b"fake mp3 bytes")

    fake = _FakeRun()
    segments = [
        {"start": 0.0, "end": 2.5, "text": "spi moy malenkiy",
         "id": 0, "seek": 0, "tokens": [1, 2], "avg_logprob": -0.1},
        {"start": 2.5, "end": 5.0, "text": "moy yasny svet",
         "id": 1, "seek": 0, "tokens": [3, 4], "avg_logprob": -0.2},
    ]

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        payload = {"text": "spi moy malenkiy moy yasny svet", "segments": segments}
        (out_dir / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
        return _Result()

    fake.add(_is_mlx_whisper_call, handle_whisper)
    fake.add(_is_ffprobe_call, lambda cmd: _Result(stdout="5.0\n"))

    result = sr.align_track(track_dir, mp3_path, None, music3_python="fake-python3", run=fake)

    assert isinstance(result, sr.SongResult)
    assert result.duration == pytest.approx(5.0)
    assert result.transcript == "spi moy malenkiy moy yasny svet"
    assert result.sections == []
    assert result.undersung is False
    assert result.raw_segments == [
        {"start": 0.0, "end": 2.5, "text": "spi moy malenkiy"},
        {"start": 2.5, "end": 5.0, "text": "moy yasny svet"},
    ]


def test_align_track_with_reference_lyrics_still_leaves_raw_segments_none(tmp_path):
    """The pre-existing, reference-lyrics path (`lyrics` a real string) is unchanged by Task 1:
    `sections`/`undersung` still come from `check_lyrics_sung`, and `raw_segments` -- the new field
    -- stays `None`, the same as every other field this function did not touch before.
    """
    track_dir = tmp_path / "track"
    mp3_path = tmp_path / "uploaded" / "suno-song.mp3"
    mp3_path.parent.mkdir(parents=True)
    mp3_path.write_bytes(b"fake mp3 bytes")

    fake = _FakeRun()
    segments = [{"start": 0.0, "end": 3.0, "text": "spi moy malenkiy"}]

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        payload = {"text": "spi moy malenkiy", "segments": segments}
        (out_dir / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
        return _Result()

    fake.add(_is_mlx_whisper_call, handle_whisper)
    fake.add(_is_ffprobe_call, lambda cmd: _Result(stdout="9.4\n"))

    result = sr.align_track(track_dir, mp3_path, "[intro]\nspi moy malenkiy",
                            music3_python="fake-python3", run=fake)

    assert result.raw_segments is None
    assert result.sections == [{"name": "intro", "start": 0.0, "end": 9.4}]


# -- no-mlx discipline --------------------------------------------------------------------------


def test_songrun_module_does_not_import_mlx():
    """`h3_48gb.songrun` is imported by the always-resident web server, not only by the worker
    while a song job is running; loading it must never pull in `mlx`/`mlx_audio`. Run in a
    subprocess so this test session's own earlier imports cannot hide a leak -- mirrors
    `test_worker_module_does_not_import_mlx`/`test_project_module_does_not_import_mlx`.
    """
    code = "import sys; import h3_48gb.songrun; print('mlx' in sys.modules)"
    result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True,
                            cwd=str(PROJECT_ROOT))
    assert result.returncode == 0, f"subprocess failed: {result.stderr}"
    assert result.stdout.strip() == "False", "importing h3_48gb.songrun must not import mlx"
