"""One song job end to end: generation, mastering, mp3, Whisper sung-lyrics check.

**Music3 is never actually run here** -- it needs the GPU, and the GPU may be busy with something
else entirely (H3 and Music3 do not coexist, design spec, "Трек"). Every `run_song`/`_generate_wav`/
`_transcribe` test substitutes a fake `run` callable in place of `subprocess.run`, mirroring
`test_worker.py`'s `spawn` substitution for the same reason. The one exception is `master`/`to_mp3`
(the ffmpeg mastering chain): those *are* exercised against a real `ffmpeg`, fed a synthetic sine
wave generated by `ffmpeg -f lavfi` -- no GPU, no external model, just the mastering chain itself.

The Whisper fuzzy-matching tests (`check_lyrics_sung` and friends) are pure functions -- no
subprocess at all -- and are built directly from the 2026-08-18 "Колыбельная" run's real facts: a
268 s take against a 295 s cap that was *not* undersung (Music3 simply ran out of lyrics), a real
Whisper mishearing ("в висках" -> "песка"), and an undersung take that looks like a sung head and
an unsung tail, not a short recording.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

from h3_48gb import songrun as sr

PROJECT_ROOT = Path(__file__).resolve().parent.parent


# -- estimate_duration / count_sections ----------------------------------------------------------


def test_count_sections_counts_every_tag_occurrence_including_repeats():
    lyrics = "[intro]\nline one\n\n[chorus]\nline two\n\n[chorus]\nline three\n\n[outro]\nline four"
    assert sr.count_sections(lyrics) == 4


def test_count_sections_on_the_real_kolybelnaya_lyrics_is_eleven():
    # intro, verse, verse, pre-chorus, chorus, verse, pre-chorus, chorus, bridge, verse, chorus,
    # outro -- but written out as the real file has it (verse/pre-chorus/chorus each split into
    # two stanzas under one tag counts as one section, matching the real lyric's own tagging).
    lyrics = """
[intro]
Спи, мой маленький, мой ясный,
Свет мой, тихий лепесток.

[verse]
Слышишь - старый верный Альдред
Тихо ходит у дверей.

За восточною стеною,
Где течёт ночной поток.

[pre-chorus]
Не пугайся, мой родимый,
Тих и тёпел этот час.

[chorus]
Спи, мой князь, мой белый сокол,
Спи, моё родное сердце.

[verse]
Слышишь - там, внизу, у двери
Ходит ветер тяжело.

[pre-chorus]
Я тебе под ушко тихо
Положу свой перстень-знак.

[chorus]
Спи, мой князь, мой белый сокол,
Спи, моё родное сердце.

[bridge]
Альдред здесь. Иди, мой милый,
Поцелуй меня в чело.

[verse]
А теперь - закрою двери,
А теперь - возьму клинок.

[chorus]
Спи, мой князь, мой белый сокол,
Ты вернёшься через век.

[outro]
Спи, мой светлый.
Спи, мой князь.
"""
    assert sr.count_sections(lyrics) == 11


def test_estimate_duration_is_28s_per_section_plus_15s_pad():
    lyrics = "[intro]\na\n\n[chorus]\nb\n\n[outro]\nc"
    assert sr.estimate_duration(lyrics) == pytest.approx(28.0 * 3 + 15.0)


def test_estimate_duration_of_untagged_lyrics_is_one_implicit_section():
    lyrics = "just some words\nwith no tags at all"
    assert sr.count_sections(lyrics) == 1
    assert sr.estimate_duration(lyrics) == pytest.approx(28.0 + 15.0)


def test_estimate_duration_of_empty_lyrics_is_just_the_pad():
    assert sr.estimate_duration("") == pytest.approx(15.0)


# -- check_lyrics_sung: fuzzy line/segment matching ----------------------------------------------


def _seg(start, end, text):
    return {"start": start, "end": end, "text": text}


def test_a_fully_sung_short_song_is_not_undersung_and_every_section_gets_a_start():
    lyrics = "[intro]\nСпи мой маленький\n\n[chorus]\nСпи мой князь мой белый сокол"
    segments = [
        _seg(0.0, 3.0, "Спи мой маленький"),
        _seg(3.0, 7.0, "Спи мой князь мой белый сокол"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=7.0)
    assert undersung is False
    assert sections == [
        {"name": "intro", "start": 0.0, "end": 3.0},
        {"name": "chorus", "start": 3.0, "end": 7.0},
    ]


def test_whisper_mishearing_v_viskah_to_peska_still_matches_at_50_percent_overlap():
    """The real 2026-08-18 example: Whisper heard "Имя древнее песка" for the sung line "Имя
    древнее в висках". 2 of the line's 4 words survive -- exactly the 50% floor
    `LINE_MATCH_THRESHOLD` is pinned to. This must match, or a correctly-sung chorus line would be
    wrongly counted against the undersung gate.
    """
    line_words = sr._word_set("Имя древнее в висках")
    heard_words = sr._word_set("Имя древнее песка")
    assert sr._overlap(line_words, heard_words) == pytest.approx(0.5)
    assert sr._overlap(line_words, heard_words) >= sr.LINE_MATCH_THRESHOLD


def test_check_lyrics_sung_matches_the_mishearing_end_to_end():
    lyrics = "[chorus]\nИмя древнее в висках"
    segments = [_seg(10.0, 13.0, "Имя древнее песка")]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=13.0)
    assert sections == [{"name": "chorus", "start": 10.0, "end": 13.0}]
    assert undersung is False


def test_268_of_295_seconds_with_a_fully_sung_tail_is_not_undersung():
    """Music3 stopping early once the lyrics run out (268s audio, 295s cap) is not undersung by
    itself -- what matters is whether the *lyrics'* tail was sung, which this fixture makes true.
    """
    lyrics = "\n".join([
        "[verse]",
        "line one",
        "line two",
        "line three",
        "[outro]",
        "line four",
        "line five",
        "line six",
    ])
    segments = [
        _seg(0.0, 10.0, "line one"),
        _seg(10.0, 20.0, "line two"),
        _seg(20.0, 30.0, "line three"),
        _seg(30.0, 40.0, "line four"),
        _seg(40.0, 50.0, "line five"),
        _seg(50.0, 60.0, "line six"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=268.0)
    assert undersung is False
    assert sections[-1]["end"] == 268.0


def test_undersung_take_has_a_sung_head_and_an_unsung_tail():
    """Shape lifted from the real "Колыбельная" undersung diagnosis: the bridge sings fine, then
    the final chorus/outro go completely unmatched while the audio (per the design spec) keeps
    playing as instrumental. Every line uses its own distinct vocabulary -- no shared filler word
    across lines -- so a line cannot spuriously clear the 50% overlap floor against an unrelated
    already-matched segment merely by sharing one common word with it.
    """
    lyrics = "\n".join([
        "[bridge]", "альдред здесь иди милый", "поцелуй меня чело",
        "[verse]", "закрою двери клинок", "король оставил веру",
        "[chorus]", "спи мой белый сокол", "имя древнее столетья",
        "[outro]", "спи мой светлый князь", "мать твоя стража",
    ])
    segments = [
        _seg(0.0, 5.0, "альдред здесь иди милый"),
        _seg(5.0, 10.0, "поцелуй меня чело"),
        _seg(10.0, 15.0, "закрою двери клинок"),
        _seg(15.0, 20.0, "король оставил веру"),
        # final chorus and outro: not sung -- only a trailing hallucinated segment with no
        # relation to the lyrics at all (e.g. a fade-out caption-credit artifact).
        _seg(20.0, 24.0, "субтитры делал дима торжок"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=24.0)
    assert undersung is True
    by_name = {s["name"]: s for s in sections}
    assert by_name["bridge"]["start"] == 0.0
    assert by_name["verse"]["start"] == 10.0
    assert by_name["chorus"]["start"] is None
    assert by_name["outro"]["start"] is None


def test_a_hallucinated_tail_segment_with_no_match_is_simply_ignored():
    lyrics = "[outro]\nSpi moy svetlyy"
    segments = [
        _seg(0.0, 2.0, "Spi moy svetlyy"),
        _seg(2.0, 6.0, "субтитры делал дима торжок"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=6.0)
    assert undersung is False
    assert sections == [{"name": "outro", "start": 0.0, "end": 6.0}]


def test_a_repeated_section_name_gets_two_separate_entries_matched_in_order():
    lyrics = "\n".join([
        "[chorus]", "spi moy knyaz",
        "[verse]", "middle line",
        "[chorus]", "spi moy knyaz",
    ])
    segments = [
        _seg(0.0, 3.0, "spi moy knyaz"),
        _seg(3.0, 6.0, "middle line"),
        _seg(6.0, 9.0, "spi moy knyaz"),
    ]
    sections, undersung = sr.check_lyrics_sung(lyrics, segments, duration=9.0)
    assert len(sections) == 3
    assert [s["name"] for s in sections] == ["chorus", "verse", "chorus"]
    assert sections[0]["start"] == 0.0
    assert sections[2]["start"] == 6.0, "second chorus must not match the first chorus's segment"


def test_undersung_threshold_is_exactly_60_percent_of_the_last_third():
    # 9 lines -> last third is lines[6:], 3 lines. 2/3 matched = 66.7% -> not undersung.
    lyrics = "\n".join(f"line{i}" for i in range(9))
    segments = [_seg(float(i), float(i) + 1, f"line{i}") for i in range(9) if i not in (7,)]
    _, undersung = sr.check_lyrics_sung(lyrics, segments)
    assert undersung is False

    # Drop one more of the last three matches (now 1/3 = 33%) -> undersung.
    segments_worse = [_seg(float(i), float(i) + 1, f"line{i}") for i in range(9) if i not in (7, 8)]
    _, undersung_worse = sr.check_lyrics_sung(lyrics, segments_worse)
    assert undersung_worse is True


def test_check_lyrics_sung_on_empty_lyrics_is_not_undersung():
    sections, undersung = sr.check_lyrics_sung("", [])
    assert sections == []
    assert undersung is False


# -- master / to_mp3: the one real-ffmpeg test -----------------------------------------------


def _make_sine_wav(path: Path, duration: float = 2.0) -> None:
    cmd = ["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi",
           "-i", f"sine=frequency=440:duration={duration}", str(path)]
    subprocess.run(cmd, check=True, capture_output=True)


def _ffprobe_duration(path: Path) -> float:
    cmd = ["ffprobe", "-v", "error", "-show_entries", "format=duration",
           "-of", "default=noprint_wrappers=1:nokey=1", str(path)]
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return float(result.stdout.strip())


def test_master_and_to_mp3_run_a_real_ffmpeg_on_a_synthetic_sine(tmp_path):
    wav = tmp_path / "sine.wav"
    _make_sine_wav(wav, duration=2.0)

    mastered = sr.master(wav, tmp_path / "sine.mastered.wav")
    assert mastered == tmp_path / "sine.mastered.wav"
    assert mastered.is_file()
    assert mastered.stat().st_size > 0
    assert _ffprobe_duration(mastered) == pytest.approx(2.0, abs=0.2)

    mp3 = sr.to_mp3(wav, tmp_path / "sine.mp3")
    mastered_mp3 = sr.to_mp3(mastered, tmp_path / "sine.mastered.mp3")
    for out in (mp3, mastered_mp3):
        assert out.is_file()
        assert out.stat().st_size > 0
        assert _ffprobe_duration(out) == pytest.approx(2.0, abs=0.3)


def test_master_raises_song_run_error_on_a_missing_input_file(tmp_path):
    with pytest.raises(sr.SongRunError):
        sr.master(tmp_path / "does-not-exist.wav", tmp_path / "out.wav")


# -- _mlx_whisper_binary ---------------------------------------------------------------------


def test_mlx_whisper_binary_is_the_console_script_next_to_the_python_interpreter(tmp_path):
    venv_bin = tmp_path / "venv" / "bin"
    venv_bin.mkdir(parents=True)
    python = venv_bin / "python"
    python.touch()
    assert sr._mlx_whisper_binary(python) == venv_bin / "mlx_whisper"


# -- fake subprocess plumbing: _generate_wav / _transcribe / run_song -------------------------


class _FakeRun:
    """Stands in for `subprocess.run`: records every call and, per call, either runs a canned
    side effect (writing whatever file a real subprocess would have written) or just returns a
    canned `CompletedProcess`-shaped result. Matches by the second argv element (the script/binary
    name), the same way a human would recognize which of `run_song`'s four subprocess calls just
    ran.
    """

    def __init__(self):
        self.calls: list[list[str]] = []
        self.handlers = {}

    def add(self, matcher, handler):
        self.handlers[matcher] = handler

    def __call__(self, cmd, **kwargs):
        self.calls.append(cmd)
        for matcher, handler in self.handlers.items():
            if matcher(cmd):
                return handler(cmd)
        raise AssertionError(f"no fake handler matched {cmd}")


class _Result:
    def __init__(self, returncode=0, stdout="", stderr=""):
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr


def _is_generate_call(cmd):
    return cmd[1] == str(sr.MUSIC3_GENERATE_SCRIPT)


def _is_mlx_whisper_call(cmd):
    return Path(cmd[0]).name == "mlx_whisper"


def _is_ffmpeg_call(cmd):
    return cmd[0] == "ffmpeg"


def test_generate_wav_parses_the_actual_duration_from_stdout(tmp_path):
    fake = _FakeRun()

    def handle_generate(cmd):
        out_path = Path(cmd[cmd.index("--output") + 1])
        out_path.write_bytes(b"fake wav bytes")
        stdout = ("[timing] model load: 3.5 s\n"
                  "[audio] " + str(out_path) + "  shape=(100, 2)  sr=44100  dur=268.3s\n")
        return _Result(returncode=0, stdout=stdout)

    fake.add(_is_generate_call, handle_generate)

    wav_path, duration = sr._generate_wav(
        "python3", "modeldir", "caption text", "lyrics text", 295.0, 30, 7, tmp_path, run=fake)

    assert wav_path == tmp_path / "song.wav"
    assert wav_path.is_file()
    assert duration == pytest.approx(268.3)
    assert (tmp_path / "caption.txt").read_text(encoding="utf-8") == "caption text"
    assert (tmp_path / "lyrics.txt").read_text(encoding="utf-8") == "lyrics text"
    assert "dur=268.3s" in (tmp_path / "gen.log").read_text(encoding="utf-8")

    [cmd] = fake.calls
    assert cmd[0] == "python3"
    assert "--duration" in cmd and cmd[cmd.index("--duration") + 1] == "295.0"
    assert "--seed" in cmd and cmd[cmd.index("--seed") + 1] == "7"


def test_generate_wav_raises_on_nonzero_exit(tmp_path):
    fake = _FakeRun()
    fake.add(_is_generate_call, lambda cmd: _Result(returncode=1, stderr="boom"))
    with pytest.raises(sr.SongRunError, match="boom"):
        sr._generate_wav("python3", "modeldir", "c", "l", 90.0, 30, 7, tmp_path, run=fake)


def test_generate_wav_raises_when_stdout_has_no_dur_line(tmp_path):
    fake = _FakeRun()
    fake.add(_is_generate_call, lambda cmd: _Result(returncode=0, stdout="no useful line here"))
    with pytest.raises(sr.SongRunError, match="dur="):
        sr._generate_wav("python3", "modeldir", "c", "l", 90.0, 30, 7, tmp_path, run=fake)


def test_transcribe_reads_back_the_json_the_cli_would_have_written(tmp_path):
    fake = _FakeRun()

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        payload = {"text": "hello", "segments": [{"start": 0.0, "end": 1.0, "text": "hello"}]}
        (out_dir / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
        return _Result(returncode=0)

    fake.add(_is_mlx_whisper_call, handle_whisper)

    data = sr._transcribe(tmp_path / "python", tmp_path / "audio.wav", tmp_path, run=fake)
    assert data["text"] == "hello"
    assert data["segments"][0]["text"] == "hello"

    [cmd] = fake.calls
    assert Path(cmd[0]).name == "mlx_whisper"
    assert "--language" in cmd and cmd[cmd.index("--language") + 1] == "ru"
    assert "--model" in cmd and cmd[cmd.index("--model") + 1] == sr.WHISPER_MODEL


def test_transcribe_raises_if_the_json_file_never_appears(tmp_path):
    fake = _FakeRun()
    fake.add(_is_mlx_whisper_call, lambda cmd: _Result(returncode=0))  # writes nothing
    with pytest.raises(sr.SongRunError):
        sr._transcribe(tmp_path / "python", tmp_path / "audio.wav", tmp_path, run=fake)


def test_transcribe_raises_on_nonzero_exit(tmp_path):
    fake = _FakeRun()
    fake.add(_is_mlx_whisper_call, lambda cmd: _Result(returncode=1, stderr="no weights"))
    with pytest.raises(sr.SongRunError, match="no weights"):
        sr._transcribe(tmp_path / "python", tmp_path / "audio.wav", tmp_path, run=fake)


# -- run_song: full orchestration with every subprocess faked ---------------------------------


def _wire_full_fake_pipeline(track_dir: Path, *, whisper_segments, whisper_text="",
                              audio_dur="90.0"):
    fake = _FakeRun()

    def handle_generate(cmd):
        out_path = Path(cmd[cmd.index("--output") + 1])
        out_path.write_bytes(b"fake raw wav")
        return _Result(stdout=f"[audio] {out_path}  shape=(1,2)  sr=44100  dur={audio_dur}s\n")

    def handle_ffmpeg(cmd):
        # the output path is always the last argv element for both master() and to_mp3()
        Path(cmd[-1]).write_bytes(b"fake ffmpeg output")
        return _Result()

    def handle_whisper(cmd):
        out_dir = Path(cmd[cmd.index("--output-dir") + 1])
        name = cmd[cmd.index("--output-name") + 1]
        payload = {"text": whisper_text, "segments": whisper_segments}
        (out_dir / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
        return _Result()

    fake.add(_is_generate_call, handle_generate)
    fake.add(_is_ffmpeg_call, handle_ffmpeg)
    fake.add(_is_mlx_whisper_call, handle_whisper)
    return fake


def test_run_song_wires_all_four_steps_into_a_song_result(tmp_path):
    track_dir = tmp_path / "track"
    segments = [{"start": 0.0, "end": 3.0, "text": "spi moy malenkiy"}]
    fake = _wire_full_fake_pipeline(track_dir, whisper_segments=segments,
                                     whisper_text="spi moy malenkiy", audio_dur="87.5")

    result = sr.run_song(
        track_dir, lyrics="[intro]\nspi moy malenkiy", caption="a lullaby", duration=90.0,
        seed=7, music3_python="fake-python3", model_dir="fake-model-dir", run=fake)

    assert isinstance(result, sr.SongResult)
    assert result.wav == track_dir / "song.wav"
    assert result.mastered_wav == track_dir / "song.mastered.wav"
    assert result.mp3 == track_dir / "song.mp3"
    assert result.mastered_mp3 == track_dir / "song.mastered.mp3"
    for path in (result.wav, result.mastered_wav, result.mp3, result.mastered_mp3):
        assert path.is_file()
    assert result.duration == pytest.approx(87.5)
    assert result.transcript == "spi moy malenkiy"
    assert result.sections == [{"name": "intro", "start": 0.0, "end": 87.5}]
    assert result.undersung is False

    # Whisper transcribed the *mastered* wav, not the raw take.
    whisper_call = next(c for c in fake.calls if Path(c[0]).name == "mlx_whisper")
    assert whisper_call[-1] == str(track_dir / "song.mastered.wav")


def test_run_song_result_fields_match_update_track_field_names():
    """`SongResult`'s field names line up 1:1 with `project.Project.update_track`'s accepted
    keywords for the fields this module actually produces -- task 3 hands the result straight
    through as `project.update_track(**{f: getattr(result, f) for f in (...)})`-shaped calls.
    """
    from h3_48gb import project as p
    result_fields = set(sr.SongResult.__dataclass_fields__)
    assert {"mp3", "mastered_mp3", "sections"} <= result_fields
    assert {"mp3", "mastered_mp3", "sections"} <= set(p._TRACK_FIELDS)


def test_run_song_propagates_a_generation_failure_as_song_run_error(tmp_path):
    fake = _FakeRun()
    fake.add(_is_generate_call, lambda cmd: _Result(returncode=1, stderr="gpu busy"))
    with pytest.raises(sr.SongRunError, match="gpu busy"):
        sr.run_song(tmp_path / "track", lyrics="[intro]\nx", caption="c", duration=30.0, seed=1,
                    music3_python="p", model_dir="m", run=fake)


def test_run_song_flags_an_undersung_take(tmp_path):
    track_dir = tmp_path / "track"
    lyrics = "\n".join([
        "[verse]", "тихо ходит альдред", "унесет тебя сквозь сон", "восточная стена",
        "[outro]", "спи мой светлый князь", "мать твоя стража", "первый страж навек",
    ])
    # only the verse sung; the outro goes to a hallucinated tail segment -- no shared filler
    # words between lines, so a later line cannot spuriously overlap an earlier match.
    segments = [
        {"start": 0.0, "end": 2.0, "text": "тихо ходит альдред"},
        {"start": 2.0, "end": 4.0, "text": "унесет тебя сквозь сон"},
        {"start": 4.0, "end": 6.0, "text": "восточная стена"},
        {"start": 6.0, "end": 10.0, "text": "субтитры делал дима торжок"},
    ]
    fake = _wire_full_fake_pipeline(track_dir, whisper_segments=segments, audio_dur="10.0")
    result = sr.run_song(track_dir, lyrics=lyrics, caption="c", duration=90.0, seed=1,
                          music3_python="p", model_dir="m", run=fake)
    assert result.undersung is True


# -- no-mlx discipline --------------------------------------------------------------------------


def test_songrun_module_does_not_import_mlx():
    """`h3_48gb.songrun` is imported by the always-resident web server, not only by the worker
    while a song job is running; loading it must never pull in `mlx`/`mlx_audio`. Run in a
    subprocess so this test session's own earlier imports cannot hide a leak -- mirrors
    `test_worker_module_does_not_import_mlx`/`test_project_module_does_not_import_mlx`.
    """
    code = "import sys; import h3_48gb.songrun; print('mlx' in sys.modules)"
    result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True,
                            cwd=str(PROJECT_ROOT))
    assert result.returncode == 0, f"subprocess failed: {result.stderr}"
    assert result.stdout.strip() == "False", "importing h3_48gb.songrun must not import mlx"
